---
title: "Rendu"
author: "Bastien"
date: "2025-02-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Initialisation

On commence par définir p un nombre d'étudiant et n le nombre de stage disponible.

```{r}
n <- sample(1:100, 1)
p <- sample(1:100, 1)
print(n)
print(p)
```

## Création de la matrice de préférence

```{r}
generer_matrice <- function(n, p) {
  # Créer une matrice vide
  mat <- matrix(nrow = p, ncol = n)
  
  # Remplir chaque ligne avec un échantillon aléatoire des nombres 1 à n
  for (i in 1:p) {
    mat[i, ] <- sample(1:n)  # Mélange des nombres de 1 à n
  }
  
  # Nommer les colonnes (a, b, c, ...)
  colnames(mat) <- letters[1:n]
  
  # Nommer les lignes (A, B, C, ...)
  rownames(mat) <- LETTERS[1:p]
  
  return(mat)
}

matrice <- generer_matrice(n, p)
```

```{r}
#minimum de chaque ligne
mat = generer_matrice(5,5)
apply(mat,1,min)

#minimum de chaque colone 
mat = generer_matrice(5,5)
apply(mat,2,min)









```






